logger:
  level: debug
  encoding: console
  color: true
  devMode: true
  disableCaller: false
  disableStacktrace: true

pidfile: ""

server:
  name: pomo
  version: debug
  type: all 
  restHost: "localhost"
  restPort: "8080"
  restPath: "api"
  unixSocket: .pomo/pomo.sock
  datetimeFormat: "2006-01-02 15:04"
  logRequests: true
client:
  type: rest
  host: localhost
  hostPort: 8081
  hostType: nextjs 

database:
  username: postgres
  password: password
  host: postgres
  port: 5432
  database: pomo
  type: sqlite
  autoCreate: true
  searchPath: ""
  sslmode: disable
  retries: 5
  sleepBetweenRetries: "7s"
  maxConnections: 40
  logQueries: true
  path: .pomo/pomo.db

cors:
  allowedOrigins:
    - "*"  
  allowedMethods:
    - "GET"
    - "POST"
    - "DELETE"
    - "OPTIONS"
  allowedHeaders:
    - "Content-Type"
    - "Authorization"
  allowCredentials: true
  maxAge: 86400

runner:
  colors: {}
  datetimeFmt: "2006-01-02 15:04"
  basePath: .pomo
  dbPath: .pomo/pomo.db
  socketPath: .pomo/pomo.sock
  iconPath: .pomo/icon.png

