name: Docker Image CI to DockerHub

on:
  push:
  push:
    branches: [feature/argoCDintegration ]
  pull_request:
    branches: [feature/argoCDintegration ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub

        uses: docker/login-action@v1 

        with:
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      -
        name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./

          file: ./Dockerfile

          push: true

          tags: niplodim/pomo:$(date %s)
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
